apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: ec2-gitops-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-pod-discovery
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: ec2-gitops-project
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-pod-discovery
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: ec2-gitops-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-pod-discovery
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitoring
